---
title: "Caso"
author: "Roberto Ruz Campos"
date: "30/11/2019"
output:
  html_document:
    keep_md: true
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

Se importa la tabla "Compustat Global Daily" con los tipos de datos correctos.
```{r}
global_daily <- read_csv("Compustat_Global_Daily.csv",
  col_types = cols(
    sedol = col_character(), 
    datadate = col_date(format = "%Y%m%d") 
  )
)
```

Tipo de variable de cada columna
```{r}
global_daily %>%
  summarise_all(class) %>%
  pivot_longer(everything(), names_to = "column", values_to = "type")
```

Vista general
```{r paged.print=TRUE}
global_daily
```

```{r}
global_daily %>% 
  count(curcdd) 
```
observaciones de cada compañía
```{r}
global_daily %>% 
  count(conm) %>% 
  arrange(conm)

global_daily %>% 
  count(conm) %>% 
  arrange(desc(n))
```

```{r}
global_daily %>% 
  filter(curcdd == "EUR") %>% 
  count(conm)
```


```{r}
global_daily %>% 
  filter(is.na(qunit)) %>% 
  count(conm)
```


```{r}
global_daily %>% 
  count(gsector)
```
industries
```{r}
global_daily %>%
  group_by(conm) %>% 
  count(sic) %>% 
  arrange(sic)

global_daily %>% 
  count(sic)
```




```{r}
global_daily %>% 
  count(conm) %>% 
  arrange(n) %>% 
  filter(n == 1)

global_daily %>% 
  select(conm, date) %>% 
  group_by(conm) %>% 
  mutate(n = n()) %>% 
  filter(n == 1)
```

```{r}
global_daily %>% 
  select(date) %>%
  distinct(date) %>% 
  arrange(date)
```
```{r}
global_daily %>% 
  filter(conm == "WAL MART DE MEXICO SA") %>% 
  select(conm, date, cshoc, cshtrd, prccd, prcstd, gsector) %>% 
  mutate(year = year(date)) %>% 
  group_by(year) %>% 
  summarise(n = n())

global_daily %>% 
  filter(conm == "WAL MART DE MEXICO SA") %>% 
  select(conm, date, cshoc, cshtrd, prccd, prcstd, gsector) %>% 
  arrange(date)

global_daily %>% 
  filter(conm == "WAL MART DE MEXICO SA") %>%  
  mutate(year = year(date)) %>% 
  filter(year == 1993) %>% 
  arrange(date) %>% 
  filter(curcdd == "MXN") 
```
```{r}
global_daily %>% 
  count(exchg)
```

```{r}
global_daily %>% 
  mutate(year = year(date)) %>% 
  #filter(conm == "CEMEX SAB DE CV") %>%
  group_by(year, conm, isin) %>% 
  summarise(num = n())
```

